# Basic dictionary of dinosaur names and types.
BASE_DINOSAURS: dict[str, str] = {
    "ammonite": "herbivore",
    "velociraptor": "carnivore",
    "pterodactyl": "carnivore",
    "t_rex": "carnivore",
    "stegosaurus": "herbivore",
    "oviraptor": "herbivore",
    "triceratops": "herbivore",
    "gallimimus": "herbivore",
    "ankylosaurus": "herbivore",
    "archaeopteryx": "carnivore",
    "smilodon": "carnivore",
    "mammoth": "herbivore",
    "therizinosaurus": "herbivore",
    "diplodocus": "herbivore",
    "dimetrodon": "carnivore",
    "parasaurolophus": "herbivore",
    "protoceratops": "herbivore",
    "iguanodon": "herbivore",
    "amargasaurus": "herbivore",
    "ceratosaurus": "carnivore",
    "incisivosaurus": "herbivore",
    "brachiosaurus": "herbivore",
    "dacentrurus": "herbivore",
    "allosaurus": "carnivore",
    "shell_don": "carnivore",
    "styracosaurus": "herbivore",
    "plesiosaurus": "carnivore",
    "kentrosaurus": "herbivore",
    "carnotaurus": "carnivore",
    "bulldosaurus": "carnivore",
    "pterocopter": "carnivore",
    "mechasaurus_rex": "carnivore",
    "yeti": "carnivore",
    "azure_dragon": "carnivore",
    "wawel_dragon": "carnivore",
    "quetzalcoatlus": "herbivore",
    "spinosaurus": "carnivore",
    "kraken": "carnivore",
    "unicorn": "herbivore",
    "spike_o_tron": "carnivore",
    "dunkleosteus": "carnivore",
    "rhizodus": "carnivore",
    "liopleurodon": "carnivore",
    "lunaspis": "carnivore",
    "megalodon": "carnivore",
    "ichthyosaurus": "carnivore",
}

DEFAULT_DINOSAURS = {
    name: {
        "type": dino_type,
        "golden_chest": False,
        "totems": 0,
        "levels": {"1": 0, "2": 0, "3": 0, "4": 0, "5": 0, "6": 0},
    }
    for name, dino_type in BASE_DINOSAURS.items()
}
